### ISSUE TITLE
Wordpress can't use cURL; need wp_remote_get and wp_remote_post instead

### ISSUE THREAD

**Issue by grundyoso** [EasyPost/easypost-php#6]
Fatal error: Uncaught exception 'Exception' with message 'EasyPost needs the CURL PHP extension.' in /var/www/awesome.dev/wp-content/plugins/woocommerce-easypost-shipping-method/easypost-php/lib/easypost.php:7 Stack trace: #0 /var/www/awesome.dev/wp-content/plugins/woocommerce-easypost-shipping-method/easypost-shipping.php(2): require_once() #1 /var/www/awesome.dev/wp-content/plugins/woocommerce-easypost-shipping-method/easypost-shipping-method.php(22): include_once('/var/www/awesom...') #2 /var/www/awesome.dev/wp-admin/plugins.php(151): include('/var/www/awesom...') #3 /var/www/awesome.dev/wp-admin/plugins.php(153): plugin_sandbox_scrape('woocommerce-eas...') #4 {main} thrown in /var/www/awesome.dev/wp-content/plugins/woocommerce-easypost-shipping-method/easypost-php/lib/easypost.php on line 7

This is due to my development server not running cURL (specifically in order to test for these Wordpress kinds of errors).

This stems from using the EasyPost PHP wrapper without adjustments made to accommodate WordPress. Remote requests should use wp_remote_post() instead of cURL.

**Comment by sawyer** [comment]
We'd be happy to accept a patch for this if anyone's interested in tackling it. I don't have a ton of WP experience so don't have a great place to start from.

**Comment by ConradGalli** [comment]
I think I have that patch, let me check.

**Comment by 2toginc** [comment]
Note wordpress users can already make easypost api calls directly via wp_remote_get() or wp_remote_post(), *completely bypassing* this client lib.  This is what a stripe plugin like stripe-for-woocommerce does (against stripe's api).

**Comment by Justintime50** [comment]
Closing due to inactivity, feel free to reopen this issue with additional information - we'd also welcome a PR to address this issue.
